### ISSUE TITLE
Font displaying weird

### ISSUE THREAD

**Issue by brianwarehime** [hohmannr/bubblified#1]
Hey, looks great, but on my end, I'm seeing the tiny question marks in squares where the bubbles would be. Is there a font that should be installed on my end to mimic the way it should be looking? Thanks!

**Comment by brianwarehime** [comment]
This is what I'm seeing on my end - https://imgur.com/L8YLXpH

**Comment by gamcoh** [comment]
yep, same

**Comment by zululee** [comment]
appears to be mac related -- the instructions for installing on mac pre-date Catalina

**Comment by rhysperry111** [comment]
I'm not sure what @hohmannr is using, but I am using the font `Source Code Pro` and it is working properly. The terminal I am using is `kitty`

**Comment by hohmannr** [comment]
Hello, thanks for the note. I updated the README to tell everyone what this theme is best used with. I use an individually patched SF Mono [nerdfont](https://github.com/ryanoasis/nerd-fonts), which I unfortunately cannot share because of the license this font ships with. But checkout the nerdfonts github, there are tons of already patched fonts for you to download. These fonts include all the necessary icons for the `git_bubble` to work properly. The bubble glyphs should be powerline glyphs, and should work with any [powerline font](https://github.com/powerline/fonts).

If these glyphs do not show up for you, try uploading your font to this [website](https://github.com/powerline/fonts). The glyphs used for the bubbles are 1274 and 1276. You can easily change these glyph by editing the theme, check the README on how to do that.

Here is a screenshot of how the charmap website looks for me using my terminal font: [https://imgur.com/a/x9xTNg1](https://imgur.com/a/x9xTNg1)

**Comment by hohmannr** [comment]
I guess this solved the issue. Closing.
