### ISSUE TITLE
Background colors not properly being used

### ISSUE THREAD

**Issue by chancecarey** [hohmannr/bubblified#5]
First, thanks for this theme, absolutely love it.

I occasionally notice some weird things like this -
![image](https://user-images.githubusercontent.com/32423458/79050031-35671580-7c1f-11ea-8801-2a797eb1b3e7.png)

The background color does not seem to be set where it should be (you can see the "border" bits of each bubbled area, but the actual background is not the same color).  I use the Nord color scheme, but have noticed the same issue with Solarized Dark and One Dark.

---

Also, unrelated, what color scheme do you use in the demo video in the readme?  Looks fantastic.

**Comment by hohmannr** [comment]
Happy Easter! Have you updated to the latest version 0.3? If not, please do so and comment if the problems persist.

Could you also please provide information on what terminal emulator you are using?

This is a weird bug, since the `bubblify` function that creates the bubbles uses the same passed in color variable for the glyph color (what you called "border") as for the background of the bubble. I think your terminal emulator may has issues with background coloring, but this is just a wild guess.

**Comment by chancecarey** [comment]
Happy Easter to you too! :-)

I've tested this using cmd as well as the new Windows Terminal.  Both using WSL2.  Looks like WSL2 has some sort of [bug](https://github.com/microsoft/terminal/issues/1160) with setting colors .. not sure if that extends to cmd.

Solarized dark -

![image](https://user-images.githubusercontent.com/32423458/79065740-7bb58680-7caa-11ea-9a73-794556967874.png)

Solarized light -

![image](https://user-images.githubusercontent.com/32423458/79065727-6c363d80-7caa-11ea-9924-581668377daa.png)

One half dark -

![image](https://user-images.githubusercontent.com/32423458/79065748-8839df00-7caa-11ea-84d8-815f0923fa46.png)

One half light -

![image](https://user-images.githubusercontent.com/32423458/79065756-91c34700-7caa-11ea-9073-b98b6891419a.png)

Most of these don't show the backgrounds at all.  Not sure if that's an issue with the color schemes or with cmd.

Which theme do you use in the gif in the readme?  Would be interested to test that theme (also it looks great) to see if it's a problem with my terminal emulator.  I'll also have a go at setting up something like conemu later today.

Thanks!

---

Tested a few other color schemes on Windows Terminal, and also getting strange behavior -

![image](https://user-images.githubusercontent.com/32423458/79065851-62f9a080-7cab-11ea-921b-36751e71b246.png)

![image](https://user-images.githubusercontent.com/32423458/79065857-69881800-7cab-11ea-91f1-839471c3f211.png)

![image](https://user-images.githubusercontent.com/32423458/79065861-73118000-7cab-11ea-9c8c-8464f1eda1b9.png)

![image](https://user-images.githubusercontent.com/32423458/79065869-7ad12480-7cab-11ea-9d01-c22d2cef4f1d.png)

![image](https://user-images.githubusercontent.com/32423458/79065874-81f83280-7cab-11ea-9164-47f2dedb1f38.png)

**Comment by chancecarey** [comment]
Ah, looks like it was just cmd/windows terminal being weird.  Using mintty and themes seem to load fine -

![image](https://user-images.githubusercontent.com/32423458/79066190-cd134500-7cad-11ea-8b92-0631816a9cfe.png)

Apologies for the issue!

Still curious about which theme you use though!

**Comment by hohmannr** [comment]
No problem, glad you resolved your issue. This is good, because I have no windows machine to test on. Yea, I was sleepy yesterday and just read the first part of your issue, sorry, my color theme is custom and can be found in my [kitty config](https://github.com/hohmannr/dotfiles/blob/master/.config/kitty/kitty.conf). There are the standard 16 colors that bash/zsh uses aswell as the fore- (text-) and background color of the terminal emulator.

I'll close this issue now.
