### ISSUE TITLE
Theme Doesn't Render Well On My Terminal

### ISSUE THREAD

**Issue by h4ckitt** [hohmannr/bubblified#8]
Hello,

I Installed Your Zsh Theme On My Terminal But It Doesn't Seem To Render Well On My Terminal

Here's A Picture

![image](https://user-images.githubusercontent.com/29712362/81448143-d4772280-9175-11ea-854f-c38d7248eca7.png)

I'll Appreciate Any Help I Can Get.

**Comment by hohmannr** [comment]
Sorry For late response.
Please Check the README, to use the default Unicode-Glyphs you need to install and use a nerd-font. To have the bubbles show, you need to change the `bubble_color` to something that is not your terminal's background color

**Comment by h4ckitt** [comment]
I'm Sorry.

Which One Of The Nerd-Fonts Do You Use?

**Comment by hohmannr** [comment]
No problem. I unfortunately cannot share my font (Apple Font, SF MONO) due to its licensing. I think [Source Code Pro](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro) comes the closest to it (it is also a great font which I used over many years previous).

You can patch your own nerd font with a script they provide on their [github](https://github.com/ryanoasis/nerd-fonts). If you also want Code Ligatures, maybe consider using [FiraCode](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode).
