### ISSUE TITLE
Which terminal emulators are compatible and why

### ISSUE THREAD

**Issue by vinicius507** [hohmannr/bubblified#9]
I've been using kitty but wanted to try alacritty. Someway alacritty can't render the bubbles, at least by default. I've been wondering what feature does a terminal emulator need to have to be able to render that and why.

**Comment by hohmannr** [comment]
The default font glyphs used for the bubbles come from a [nerdfont](https://github.com/ryanoasis/nerd-fonts) (check them out, there are a lot of nice fonts with a lot of icons etc. added). There are two main ways why a terminal emulator does not display the bubbles. Firstly, because you do not have a nerdfont (and you are using the default glyphs). Secondly, the background color of your terminal is the same as the color used to render the bubble (I think this might be your problem when the bubbles worked in kitty). To solve it, you have two options:
1. Go into the `bubblified.zsh-theme` and change the `bubble_color` variable.
2. Go into your terminal emulators config and change the background color to something else that is not the same color as `bubble_color`

**Comment by vinicius507** [comment]
Oh, yeah, I think I forgot about that and just bugged out. Thank you for your explanation though :)
